# Generated by Django 3.1.6 on 2025-02-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mstdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=12)),
                ('gender', models.CharField(max_length=40)),
                ('dob', models.BigIntegerField()),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
